### ISSUE TITLE
 method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

### ISSUE THREAD

**Issue by renatoramos7** [ankitdubey021/GPSTracker#3]
Please look this part my Friend. 
By the way: nice job  👍 
All Permissions is ok. 
Error:
Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

 private void getAddress() {
        try {
            Geocoder geocoder = new Geocoder(this, Locale.getDefault()); XXXX >> This part.
            List<Address> addresses = geocoder.getFromLocation(this.latitude, this.longitude, 1);
            this.address = ((Address)addresses.get(0)).getAddressLine(0);
            this.zip = ((Address)addresses.get(0)).getPostalCode();
            this.cityName = ((Address)addresses.get(0)).getLocality();
            this.countryCode = ((Address)addresses.get(0)).getCountryCode();
            this.countryName = ((Address)addresses.get(0)).getCountryName();
            this.state = ((Address)addresses.get(0)).getAdminArea();
            this.macAddress = IPTracker.getMACAddress("wlan0");
            this.ipAddress = IPTracker.getIPAddress(true);
        } catch (Exception var3) {
            System.out.println("------------->Exception");
            var3.printStackTrace();
        }

    }

**Comment by robertdroid** [comment]
I have the same error!! in 
tracker.getLatitude()

**Comment by ankitdubey021** [comment]
**Fixed the issue**
Sorry for the problem you faced @renatoramos7  and @pepitweet .

the problem is resolved and well tested in the new version of GPSTracker 2.0 
please let me know if you are still facing any issue.
thank you.

**Comment by FEKimseongeun** [comment]
@renatoramos7  
Did you solve the problem? I also have the same error. I wonder if there are other solutions.
